version: "3"
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    deploy:
      placement:
        constraints: [node.role == manager]
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      placement:
        constraints: [node.role == manager]
  consumer:
    image: consumer:v1
    ports:
      - "8081:8081"
    environment:
      bootstrapAddress: PLAINTEXT://kafka:9092
  producer:
    image: producer:v1
    ports:
      - "8082:8082"
    environment:
      bootstrapAddress: PLAINTEXT://kafka:9092