version: '3.1'
services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper
    hostname: zoo2
    ports:
      - 2182:2182
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_PORT: 2182
  zoo3:
    image: zookeeper
    hostname: zoo3
    ports:
      - 2183:2183
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_PORT: 2183
  kafka1:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 1
  kafka2:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9093:9093"
    hostname: kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
  kafka3:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9094:9094"
    hostname: kafka3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
  consumer:
    image: 2124211/consumer:v1
    ports:
      - "8081:8081"
    environment:
      bootstrapAddress: PLAINTEXT://kafka3:9094,PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9093
  producer:
    image: 2124211/producer:v1
    ports:
      - "8082:8082"
    environment:
      bootstrapAddress: PLAINTEXT://kafka3:9094,PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9093