version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.108:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.108:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consumer:
    image: 2124211/consumer:v1
    ports:
      - "8081:8081"
    networks:
      - webnet
  producer:
    image: 2124211/producer:v1
    ports:
      - "8082:8082"
    networks:
      - webnet
networks:
  webnet: